# Generated by Django 4.2.7 on 2025-08-14 08:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "video_file",
                    models.FileField(
                        upload_to=videos.models.video_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "webm",
                                ]
                            )
                        ],
                        verbose_name="video file",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="duration in seconds"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="file size in bytes"
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="resolution"
                    ),
                ),
                (
                    "format",
                    models.CharField(blank=True, max_length=10, verbose_name="format"),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="is processed"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="processing status",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="processing error"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="is public"),
                ),
                (
                    "allow_download",
                    models.BooleanField(default=False, verbose_name="allow download"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
                "ordering": ["lesson__order"],
            },
        ),
        migrations.CreateModel(
            name="VideoStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="session id"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_watch_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total watch time in seconds"
                    ),
                ),
                (
                    "current_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current position in seconds"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ip address"
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("1080p", "1080p"),
                            ("720p", "720p"),
                            ("480p", "480p"),
                            ("360p", "360p"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="quality",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "video stream",
                "verbose_name_plural": "video streams",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "timestamp",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="timestamp in seconds"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="is approved"),
                ),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="is flagged"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="videos.videocomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "video comment",
                "verbose_name_plural": "video comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(
                        default=0, verbose_name="timestamp in seconds"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "video bookmark",
                "verbose_name_plural": "video bookmarks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "video")},
            },
        ),
        migrations.CreateModel(
            name="VideoAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="date")),
                (
                    "total_views",
                    models.PositiveIntegerField(default=0, verbose_name="total views"),
                ),
                (
                    "unique_views",
                    models.PositiveIntegerField(default=0, verbose_name="unique views"),
                ),
                (
                    "total_watch_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total watch time in seconds"
                    ),
                ),
                (
                    "average_watch_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="average watch time in seconds"
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of viewers who completed the video",
                        max_digits=5,
                        verbose_name="completion rate",
                    ),
                ),
                (
                    "mobile_views",
                    models.PositiveIntegerField(default=0, verbose_name="mobile views"),
                ),
                (
                    "desktop_views",
                    models.PositiveIntegerField(
                        default=0, verbose_name="desktop views"
                    ),
                ),
                (
                    "tablet_views",
                    models.PositiveIntegerField(default=0, verbose_name="tablet views"),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "video analytics",
                "verbose_name_plural": "video analytics",
                "ordering": ["-date"],
                "unique_together": {("video", "date")},
            },
        ),
    ]
